"""
office_seed_data.py
-------------------
Curated list of real Nepali government offices seeded into the
`government_offices` table for the "Find Nearest Office" feature.

This is STATIC, hand-curated catalog data (no live Google Places search).
Coordinates are WGS84 approximations at street-office level; phone numbers and
service hours come from publicly available government directories and should
be re-verified against official sources before deployment.
"""

# Service/office tag keys used by GET /api/v1/offices/nearby and the Android app.
# Openers: citizenship, nid, passport, driving_license + category fallbacks.
TAG_CITIZENSHIP = "citizenship,identity"
TAG_NID = "nid,identity"
TAG_PASSPORT = "passport,identity"
TAG_DRIVING = "driving_license,transport"
TAG_BUSINESS_REGISTRATION = "business_registration,business"


GOVERNMENT_OFFICES = [
    # ── DISTRICT ADMINISTRATION OFFICES (citizenship, NID) ──────────────────
    {
        "name": "Kathmandu District Administration Office",
        "name_ne": "जिल्ला प्रशासन कार्यालय काठमाडौं",
        "office_type": "District Administration Office (DAO)",
        "service_tags": TAG_CITIZENSHIP,
        "district": "Kathmandu",
        "address": "Babarmahal, Kathmandu",
        "latitude": 27.6915,
        "longitude": 85.3240,
        "phone": "01-4262445",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
    },
    {
        "name": "Lalitpur District Administration Office",
        "name_ne": "जिल्ला प्रशासन कार्यालय ललितपुर",
        "office_type": "District Administration Office (DAO)",
        "service_tags": TAG_CITIZENSHIP,
        "district": "Lalitpur",
        "address": "Manbhawan, Lalitpur",
        "latitude": 27.6685,
        "longitude": 85.3180,
        "phone": "01-5521204",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
    },
    {
        "name": "Bhaktapur District Administration Office",
        "name_ne": "जिल्ला प्रशासन कार्यालय भक्तपुर",
        "office_type": "District Administration Office (DAO)",
        "service_tags": TAG_CITIZENSHIP,
        "district": "Bhaktapur",
        "address": "Byasi, Bhaktapur",
        "latitude": 27.6728,
        "longitude": 85.4285,
        "phone": "01-6610260",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
    },
    {
        "name": "Area Administration Office Sankhu",
        "name_ne": "इलाका प्रशासन कार्यालय साँखु",
        "office_type": "Area Administration Office",
        "service_tags": TAG_CITIZENSHIP,
        "district": "Kathmandu",
        "address": "Sankhu, Shankharapur, Kathmandu",
        "latitude": 27.7328,
        "longitude": 85.4627,
        "phone": "01-4450233",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
    },
    {
        "name": "Area Administration Office Gotikhel",
        "name_ne": "इलाका प्रशासन कार्यालय गोटीखेल",
        "office_type": "Area Administration Office",
        "service_tags": TAG_CITIZENSHIP,
        "district": "Lalitpur",
        "address": "Gotikhel, Mahankal, Lalitpur",
        "latitude": 27.4647,
        "longitude": 85.3512,
        "phone": "01-6200234",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
    },
    {
        "name": "Kaski District Administration Office",
        "name_ne": "जिल्ला प्रशासन कार्यालय कास्की",
        "office_type": "District Administration Office (DAO)",
        "service_tags": TAG_CITIZENSHIP,
        "district": "Kaski",
        "address": "Bagar Pokhara, Kaski",
        "latitude": 28.2096,
        "longitude": 83.9856,
        "phone": "061-464134",
        "hours": "10:00–17:00 (Sun–Fri)",
    },
    {
        "name": "Morang District Administration Office",
        "name_ne": "जिल्ला प्रशासन कार्यालय मोरङ",
        "office_type": "District Administration Office (DAO)",
        "service_tags": TAG_CITIZENSHIP,
        "district": "Morang",
        "address": "Mahendra Highway, Biratnagar, Morang",
        "latitude": 26.4525,
        "longitude": 87.2718,
        "phone": "021-533111",
        "hours": "10:00–17:00 (Sun–Fri)",
    },
    {
        "name": "Rupandehi District Administration Office",
        "name_ne": "जिल्ला प्रशासन कार्यालय रुपन्देही",
        "office_type": "District Administration Office (DAO)",
        "service_tags": TAG_CITIZENSHIP,
        "district": "Rupandehi",
        "address": "Bagiya, Butwal, Rupandehi",
        "latitude": 27.7005,
        "longitude": 83.4612,
        "phone": "071-544104",
        "hours": "10:00–17:00 (Sun–Fri)",
    },
    {
        "name": "Chitwan District Administration Office",
        "name_ne": "जिल्ला प्रशासन कार्यालय चितवन",
        "office_type": "District Administration Office (DAO)",
        "service_tags": TAG_CITIZENSHIP,
        "district": "Chitwan",
        "address": "Bharatpur, Chitwan",
        "latitude": 27.6833,
        "longitude": 84.4333,
        "phone": "056-521796",
        "hours": "10:00–17:00 (Sun–Fri)",
    },
    {
        "name": "Makwanpur District Administration Office",
        "name_ne": "जिल्ला प्रशासन कार्यालय मकवानपुर",
        "office_type": "District Administration Office (DAO)",
        "service_tags": TAG_CITIZENSHIP,
        "district": "Makwanpur",
        "address": "Hetauda, Makwanpur",
        "latitude": 27.4281,
        "longitude": 85.0322,
        "phone": "057-527901",
        "hours": "10:00–17:00 (Sun–Fri)",
    },
    {
        "name": "Banke District Administration Office",
        "name_ne": "जिल्ला प्रशासन कार्यालय बाँके",
        "office_type": "District Administration Office (DAO)",
        "service_tags": TAG_CITIZENSHIP,
        "district": "Banke",
        "address": "Nepalgunj, Banke",
        "latitude": 28.0585,
        "longitude": 81.6120,
        "phone": "081-525503",
        "hours": "10:00–17:00 (Sun–Fri)",
    },
    {
        "name": "Surkhet District Administration Office",
        "name_ne": "जिल्ला प्रशासन कार्यालय सुर्खेत",
        "office_type": "District Administration Office (DAO)",
        "service_tags": TAG_CITIZENSHIP,
        "district": "Surkhet",
        "address": "Birendranagar, Surkhet",
        "latitude": 28.5928,
        "longitude": 81.6333,
        "phone": "083-524606",
        "hours": "10:00–17:00 (Sun–Fri)",
    },
    {
        "name": "Kailali District Administration Office",
        "name_ne": "जिल्ला प्रशासन कार्यालय कैलाली",
        "office_type": "District Administration Office (DAO)",
        "service_tags": TAG_CITIZENSHIP,
        "district": "Kailali",
        "address": "Dhangadhi, Kailali",
        "latitude": 28.6833,
        "longitude": 80.6167,
        "phone": "091-522121",
        "hours": "10:00–17:00 (Sun–Fri)",
    },

    # ── PASSPORT / RAHADANI OFFICES ────────────────────────────────────────
    {
        "name": "Department of Passports (Rahadani Bhaban)",
        "name_ne": "राहदानी विभाग",
        "office_type": "Department of Passports",
        "service_tags": TAG_PASSPORT,
        "district": "Kathmandu",
        "address": "Tripureshwor, Kathmandu",
        "latitude": 27.6950,
        "longitude": 85.3169,
        "phone": "01-4245273",
        "hours": "09:00–15:00 (Sun–Thu)",
        "is_active": False,
    },
    {
        "name": "Department of Passports (DoP)",
        "name_ne": "राहदानी विभाग",
        "office_type": "Department of Passports",
        "service_tags": TAG_PASSPORT,
        "district": "Kathmandu",
        "address": "Tripureshwor, Kathmandu",
        "latitude": 27.6946,
        "longitude": 85.3146,
        "phone": "01-5970365",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
    },
    {
        "name": "Passport Section - DAO Kathmandu",
        "name_ne": "राहदानी शाखा, जिल्ला प्रशासन कार्यालय काठमाडौं",
        "office_type": "DAO Passport Section",
        "service_tags": TAG_PASSPORT,
        "district": "Kathmandu",
        "address": "Babarmahal, Kathmandu",
        "latitude": 27.6915,
        "longitude": 85.3240,
        "phone": "01-4262445",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
    },
    {
        "name": "Passport Section - DAO Lalitpur",
        "name_ne": "राहदानी शाखा, जिल्ला प्रशासन कार्यालय ललितपुर",
        "office_type": "DAO Passport Section",
        "service_tags": TAG_PASSPORT,
        "district": "Lalitpur",
        "address": "Manbhawan, Lalitpur",
        "latitude": 27.6685,
        "longitude": 85.3180,
        "phone": "01-5521204",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
    },
    {
        "name": "Passport Section - DAO Bhaktapur",
        "name_ne": "राहदानी शाखा, जिल्ला प्रशासन कार्यालय भक्तपुर",
        "office_type": "DAO Passport Section",
        "service_tags": TAG_PASSPORT,
        "district": "Bhaktapur",
        "address": "Byasi, Bhaktapur",
        "latitude": 27.6728,
        "longitude": 85.4285,
        "phone": "01-6610260",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
    },
    {
        "name": "Regional Passport Office - Biratnagar",
        "name_ne": "क्षेत्रीय राहदानी कार्यालय विराटनगर",
        "office_type": "Regional Passport Office",
        "service_tags": TAG_PASSPORT,
        "district": "Morang",
        "address": "Jhoda, Biratnagar, Morang",
        "latitude": 26.4484,
        "longitude": 87.2791,
        "phone": "021-531112",
        "hours": "10:00–15:00 (Sun–Thu)",
    },
    {
        "name": "Regional Passport Office - Chitwan",
        "name_ne": "क्षेत्रीय राहदानी कार्यालय चितवन",
        "office_type": "Regional Passport Office",
        "service_tags": TAG_PASSPORT,
        "district": "Chitwan",
        "address": "Bharatpur, Chitwan",
        "latitude": 27.6777,
        "longitude": 84.4323,
        "phone": "056-524322",
        "hours": "10:00–15:00 (Sun–Thu)",
    },
    {
        "name": "Regional Passport Office - Janakpur",
        "name_ne": "क्षेत्रीय राहदानी कार्यालय जनकपुर",
        "office_type": "Regional Passport Office",
        "service_tags": TAG_PASSPORT,
        "district": "Dhanusa",
        "address": "Janakpur, Dhanusa",
        "latitude": 26.7317,
        "longitude": 85.9253,
        "phone": "041-522112",
        "hours": "10:00–15:00 (Sun–Thu)",
    },
    {
        "name": "Regional Passport Office - Butwal",
        "name_ne": "क्षेत्रीय राहदानी कार्यालय बुटवल",
        "office_type": "Regional Passport Office",
        "service_tags": TAG_PASSPORT,
        "district": "Rupandehi",
        "address": "Butwal, Rupandehi",
        "latitude": 27.7005,
        "longitude": 83.4612,
        "phone": "071-544108",
        "hours": "10:00–15:00 (Sun–Thu)",
    },
    {
        "name": "Regional Passport Office - Pokhara",
        "name_ne": "क्षेत्रीय राहदानी कार्यालय पोखरा",
        "office_type": "Regional Passport Office",
        "service_tags": TAG_PASSPORT,
        "district": "Kaski",
        "address": "Pokhara, Kaski",
        "latitude": 28.2096,
        "longitude": 83.9856,
        "phone": "061-464210",
        "hours": "10:00–15:00 (Sun–Thu)",
    },
    {
        "name": "Regional Passport Office - Dhangadhi",
        "name_ne": "क्षेत्रीय राहदानी कार्यालय धनगढी",
        "office_type": "Regional Passport Office",
        "service_tags": TAG_PASSPORT,
        "district": "Kailali",
        "address": "Dhangadhi, Kailali",
        "latitude": 28.6833,
        "longitude": 80.6167,
        "phone": "091-520112",
        "hours": "10:00–15:00 (Sun–Thu)",
    },
    {
        "name": "Regional Passport Office - Nepalgunj",
        "name_ne": "क्षेत्रीय राहदानी कार्यालय नेपालगन्ज",
        "office_type": "Regional Passport Office",
        "service_tags": TAG_PASSPORT,
        "district": "Banke",
        "address": "Nepalgunj, Banke",
        "latitude": 28.0585,
        "longitude": 81.6120,
        "phone": "081-526602",
        "hours": "10:00–15:00 (Sun–Thu)",
    },

    # ── NID / NATIONAL IDENTIFICATION ───────────────────────────────────────
    {
        "name": "DoNIDCR Central Office",
        "name_ne": "राष्ट्रिय परिचयपत्र तथा नागरिक दर्ता विभाग",
        "office_type": "DoNIDCR Enrollment Center",
        "service_tags": TAG_NID,
        "district": "Kathmandu",
        "address": "Tripureshwor, Kathmandu",
        "latitude": 27.6947,
        "longitude": 85.3158,
        "phone": "01-4244560",
        "hours": "10:00–17:00 (Sun–Fri)",
        "is_active": False,
    },
    {
        "name": "Department of National ID and Civil Registration (DoNIDCR)",
        "name_ne": "राष्ट्रिय परिचयपत्र तथा पञ्जीकरण विभाग",
        "office_type": "Department HQ",
        "service_tags": TAG_NID,
        "district": "Kathmandu",
        "address": "Singha Durbar / Babarmahal, Kathmandu",
        "latitude": 27.6930,
        "longitude": 85.3220,
        "phone": "01-4200014",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
    },
    {
        "name": "NID Enrollment Center - Rastriya Sabha Griha",
        "name_ne": "राष्ट्रिय परिचयपत्र विवरण दर्ता केन्द्र, राष्ट्रिय सभागृह",
        "office_type": "NID Enrollment Center",
        "service_tags": TAG_NID,
        "district": "Kathmandu",
        "address": "Pradarshani Marg, Kathmandu",
        "latitude": 27.7029,
        "longitude": 85.3173,
        "phone": "01-4200014",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
    },
    {
        "name": "NID Enrollment Center - Narayanhiti Palace Premises",
        "name_ne": "राष्ट्रिय परिचयपत्र विवरण दर्ता केन्द्र, नारायणहिटी दरबार परिसर",
        "office_type": "NID Enrollment Center",
        "service_tags": TAG_NID,
        "district": "Kathmandu",
        "address": "Durbar Marg, Kathmandu",
        "latitude": 27.7123,
        "longitude": 85.3206,
        "phone": "01-4200014",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
    },
    {
        "name": "NID Biometric Station - DAO Kathmandu",
        "name_ne": "राष्ट्रिय परिचयपत्र दर्ता शाखा, जिल्ला प्रशासन कार्यालय काठमाडौं",
        "office_type": "NID Enrollment Station",
        "service_tags": TAG_NID,
        "district": "Kathmandu",
        "address": "Babarmahal, Kathmandu",
        "latitude": 27.6915,
        "longitude": 85.3240,
        "phone": "01-4262445",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
    },
    {
        "name": "NID Biometric Station - DAO Lalitpur",
        "name_ne": "राष्ट्रिय परिचयपत्र दर्ता शाखा, जिल्ला प्रशासन कार्यालय ललितपुर",
        "office_type": "NID Enrollment Station",
        "service_tags": TAG_NID,
        "district": "Lalitpur",
        "address": "Manbhawan, Lalitpur",
        "latitude": 27.6685,
        "longitude": 85.3180,
        "phone": "01-5521204",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
    },
    {
        "name": "NID Biometric Station - DAO Bhaktapur",
        "name_ne": "राष्ट्रिय परिचयपत्र दर्ता शाखा, जिल्ला प्रशासन कार्यालय भक्तपुर",
        "office_type": "NID Enrollment Station",
        "service_tags": TAG_NID,
        "district": "Bhaktapur",
        "address": "Byasi, Bhaktapur",
        "latitude": 27.6728,
        "longitude": 85.4285,
        "phone": "01-6610260",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
    },
    {
        "name": "NID Enrollment Center - Lalitpur",
        "name_ne": "राष्ट्रिय परिचयपत्र दर्ता केन्द्र ललितपुर",
        "office_type": "DoNIDCR Enrollment Center",
        "service_tags": TAG_NID,
        "district": "Lalitpur",
        "address": "Pulchowk, Lalitpur",
        "latitude": 27.6789,
        "longitude": 85.3190,
        "phone": "01-5544901",
        "hours": "10:00–16:00 (Sun–Fri)",
    },
    {
        "name": "NID Enrollment Center - Pokhara",
        "name_ne": "राष्ट्रिय परिचयपत्र दर्ता केन्द्र पोखरा",
        "office_type": "DoNIDCR Enrollment Center",
        "service_tags": TAG_NID,
        "district": "Kaski",
        "address": "Bagar Pokhara, Kaski",
        "latitude": 28.2096,
        "longitude": 83.9856,
        "phone": "061-464136",
        "hours": "10:00–16:00 (Sun–Fri)",
    },
    {
        "name": "NID Enrollment Center - Biratnagar",
        "name_ne": "राष्ट्रिय परिचयपत्र दर्ता केन्द्र विराटनगर",
        "office_type": "DoNIDCR Enrollment Center",
        "service_tags": TAG_NID,
        "district": "Morang",
        "address": "Mahendra Highway, Biratnagar, Morang",
        "latitude": 26.4525,
        "longitude": 87.2718,
        "phone": "021-533114",
        "hours": "10:00–16:00 (Sun–Fri)",
    },

    # ── TRANSPORT / DRIVING LICENSE ─────────────────────────────────────────
    {
        "name": "Department of Transport Management",
        "name_ne": "सवारी तथा यातायात व्यवस्था विभाग",
        "office_type": "Department of Transport Management (DOTM)",
        "service_tags": TAG_DRIVING,
        "district": "Lalitpur",
        "address": "Ekantakuna, Lalitpur",
        "latitude": 27.6656,
        "longitude": 85.3184,
        "phone": "01-5536013",
        "hours": "10:00–17:00 (Sun–Fri)",
        "is_active": False,
    },
    {
        "name": "Transport Management Office (Driving License) Ekantakuna",
        "name_ne": "यातायात व्यवस्था कार्यालय (सवारी चालक अनुमतिपत्र) एकान्तकुना",
        "office_type": "Transport Management Office (TMO)",
        "service_tags": TAG_DRIVING,
        "district": "Lalitpur",
        "address": "Ekantakuna, Lalitpur",
        "latitude": 27.6653,
        "longitude": 85.3113,
        "phone": "01-5527967",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
    },
    {
        "name": "Transport Management Office (Driving License) Chabahil",
        "name_ne": "यातायात व्यवस्था कार्यालय (सवारी चालक अनुमतिपत्र) चाबहिल",
        "office_type": "Transport Management Office (TMO)",
        "service_tags": TAG_DRIVING,
        "district": "Kathmandu",
        "address": "Sukedhara / Chabahil, Kathmandu",
        "latitude": 27.7262,
        "longitude": 85.3485,
        "phone": "01-4378772",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
    },
    {
        "name": "Transport Management Office (Driving License) Thulobharyang",
        "name_ne": "यातायात व्यवस्था कार्यालय (सवारी चालक अनुमतिपत्र) ठूलोभर्याङ्ग",
        "office_type": "Transport Management Office (TMO)",
        "service_tags": TAG_DRIVING,
        "district": "Kathmandu",
        "address": "Thulobharyang, Swayambhu, Kathmandu",
        "latitude": 27.7182,
        "longitude": 85.2755,
        "phone": "01-4279092",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
    },
    {
        "name": "Transport Management Office (Driving License) Radhe Radhe",
        "name_ne": "यातायात व्यवस्था कार्यालय (सवारी चालक अनुमतिपत्र) राधे राधे",
        "office_type": "Transport Management Office (TMO)",
        "service_tags": TAG_DRIVING,
        "district": "Bhaktapur",
        "address": "Radhe Radhe, Madhyapur Thimi, Bhaktapur",
        "latitude": 27.6749,
        "longitude": 85.3974,
        "phone": "01-6638064",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
    },
    {
        "name": "Transport Management Office - Pokhara",
        "name_ne": "यातायात व्यवस्था कार्यालय पोखरा",
        "office_type": "DOTM Regional Office",
        "service_tags": TAG_DRIVING,
        "district": "Kaski",
        "address": "Srijana Chowk, Pokhara, Kaski",
        "latitude": 28.2177,
        "longitude": 83.9869,
        "phone": "061-540323",
        "hours": "10:00–17:00 (Sun–Fri)",
    },
    {
        "name": "Transport Management Office - Biratnagar",
        "name_ne": "यातायात व्यवस्था कार्यालय विराटनगर",
        "office_type": "DOTM Regional Office",
        "service_tags": TAG_DRIVING,
        "district": "Morang",
        "address": "Jhoda, Biratnagar, Morang",
        "latitude": 26.4484,
        "longitude": 87.2791,
        "phone": "021-531151",
        "hours": "10:00–17:00 (Sun–Fri)",
    },
    {
        "name": "Transport Management Office - Butwal",
        "name_ne": "यातायात व्यवस्था कार्यालय बुटवल",
        "office_type": "DOTM Regional Office",
        "service_tags": TAG_DRIVING,
        "district": "Rupandehi",
        "address": "Butwal, Rupandehi",
        "latitude": 27.6912,
        "longitude": 83.4549,
        "phone": "071-540055",
        "hours": "10:00–17:00 (Sun–Fri)",
    },
    {
        "name": "Transport Management Office - Nepalgunj",
        "name_ne": "यातायात व्यवस्था कार्यालय नेपालगन्ज",
        "office_type": "DOTM Regional Office",
        "service_tags": TAG_DRIVING,
        "district": "Banke",
        "address": "Nepalgunj, Banke",
        "latitude": 28.0585,
        "longitude": 81.6120,
        "phone": "081-526602",
        "hours": "10:00–17:00 (Sun–Fri)",
    },
    {
        "name": "Transport Management Office - Dhangadhi",
        "name_ne": "यातायात व्यवस्था कार्यालय धनगढी",
        "office_type": "DOTM Regional Office",
        "service_tags": TAG_DRIVING,
        "district": "Kailali",
        "address": "Dhangadhi, Kailali",
        "latitude": 28.6833,
        "longitude": 80.6167,
        "phone": "091-520455",
        "hours": "10:00–17:00 (Sun–Fri)",
    },
    {
        "name": "Transport Management Office - Hetauda",
        "name_ne": "यातायात व्यवस्था कार्यालय हेटौंडा",
        "office_type": "DOTM Regional Office",
        "service_tags": TAG_DRIVING,
        "district": "Makwanpur",
        "address": "Hetauda, Makwanpur",
        "latitude": 27.4281,
        "longitude": 85.0322,
        "phone": "057-524510",
        "hours": "10:00–17:00 (Sun–Fri)",
    },
    {
        "name": "Transport Management Office - Chitwan",
        "name_ne": "यातायात व्यवस्था कार्यालय चितवन",
        "office_type": "DOTM Regional Office",
        "service_tags": TAG_DRIVING,
        "district": "Chitwan",
        "address": "Bharatpur, Chitwan",
        "latitude": 27.6777,
        "longitude": 84.4323,
        "phone": "056-521796",
        "hours": "10:00–17:00 (Sun–Fri)",
    },

    # ── WARD / MUNICIPALITY (recommendation for citizenship) ────────────────
    {
        "name": "Kathmandu Metropolitan City Office",
        "name_ne": "काठमाडौं महानगरपालिका कार्यालय",
        "office_type": "Metropolitan City (Ward Offices)",
        "service_tags": TAG_CITIZENSHIP,
        "district": "Kathmandu",
        "address": "Durbarmarg, Kathmandu",
        "latitude": 27.7067,
        "longitude": 85.3161,
        "phone": "01-4265180",
        "hours": "10:00–17:00 (Sun–Fri)",
    },
    {
        "name": "Lalitpur Metropolitan City Office",
        "name_ne": "ललितपुर महानगरपालिका कार्यालय",
        "office_type": "Metropolitan City (Ward Offices)",
        "service_tags": TAG_CITIZENSHIP,
        "district": "Lalitpur",
        "address": "Mangal Bazar, Lalitpur",
        "latitude": 27.6746,
        "longitude": 85.3199,
        "phone": "01-5520555",
        "hours": "10:00–17:00 (Sun–Fri)",
    },
    {
        "name": "Pokhara Metropolitan City Office",
        "name_ne": "पोखरा महानगरपालिका कार्यालय",
        "office_type": "Metropolitan City (Ward Offices)",
        "service_tags": TAG_CITIZENSHIP,
        "district": "Kaski",
        "address": "Bagar Pokhara, Kaski",
        "latitude": 28.2121,
        "longitude": 83.9659,
        "phone": "061-431112",
        "hours": "10:00–17:00 (Sun–Fri)",
    },

    # ── COMPANY & INDUSTRY REGISTRATION (business registration) ────────────────
    {
        "name": "Office of the Company Registrar (OCR)",
        "name_ne": "कम्पनी रजिष्ट्रारको कार्यालय",
        "office_type": "Company Registrar Office",
        "service_tags": TAG_BUSINESS_REGISTRATION,
        "district": "Kathmandu",
        "address": "Tripureshwor, Kathmandu",
        "latitude": 27.6953,
        "longitude": 85.3148,
        "phone": "01-5367256",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
        "note": "Primary body for company incorporation (Memorandum & Articles, certificate).",
    },
    {
        "name": "Department of Industry (DoI)",
        "name_ne": "उद्योग विभाग",
        "office_type": "Department of Industry",
        "service_tags": TAG_BUSINESS_REGISTRATION,
        "district": "Kathmandu",
        "address": "Tripureshwor, Kathmandu",
        "latitude": 27.6942,
        "longitude": 85.3135,
        "phone": "01-5356212",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
        "note": "Approvals for industrial / foreign-investment (FDI) enterprises.",
    },
    {
        "name": "Department of Commerce, Supplies and Consumer Protection",
        "name_ne": "वाणिज्य, आपूर्ति तथा उपभोक्ता संरक्षण विभाग",
        "office_type": "Department of Commerce",
        "service_tags": TAG_BUSINESS_REGISTRATION,
        "district": "Kathmandu",
        "address": "Babarmahal, Kathmandu",
        "latitude": 27.6908,
        "longitude": 85.3242,
        "phone": "01-5343939",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
    },
    {
        "name": "Industry and Commerce Office - Kathmandu (CSIO)",
        "name_ne": "उद्योग तथा वाणिज्य कार्यालय, काठमाडौँ",
        "office_type": "CSIO / Cottage & Small Industry Office",
        "service_tags": TAG_BUSINESS_REGISTRATION,
        "district": "Kathmandu",
        "address": "Tripureshwor, Kathmandu",
        "latitude": 27.6948,
        "longitude": 85.3139,
        "phone": "01-5359875",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
        "note": "Cottage & small industry registration is handled by dedicated Industry and Commerce Offices (CSIO), not the Company Registrar.",
    },
    {
        "name": "Industry and Commerce Office - Lalitpur (CSIO)",
        "name_ne": "उद्योग तथा वाणिज्य कार्यालय, ललितपुर",
        "office_type": "CSIO / Cottage & Small Industry Office",
        "service_tags": TAG_BUSINESS_REGISTRATION,
        "district": "Lalitpur",
        "address": "Patan Industrial Estate, Lagankhel, Lalitpur",
        "latitude": 27.6669,
        "longitude": 85.3225,
        "phone": "01-5423452",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
        "note": "Cottage & small industry registration is handled by dedicated Industry and Commerce Offices (CSIO), not the Company Registrar.",
    },
    {
        "name": "Industry and Commerce Office - Bhaktapur (CSIO)",
        "name_ne": "उद्योग तथा वाणिज्य कार्यालय, भक्तपुर",
        "office_type": "CSIO / Cottage & Small Industry Office",
        "service_tags": TAG_BUSINESS_REGISTRATION,
        "district": "Bhaktapur",
        "address": "Byasi / Sallaghari, Bhaktapur",
        "latitude": 27.6740,
        "longitude": 85.4215,
        "phone": "01-6610488",
        "hours": "10:00–17:00 (Sun–Thu), 10:00–15:00 (Fri)",
        "note": "Cottage & small industry registration is handled by dedicated Industry and Commerce Offices (CSIO), not the Company Registrar.",
    },
]