# -*- coding: utf-8 -*-
"""
step_templates.py
-----------------
English step-level progress checklists used when a user starts an application
for a service. Keyed by gov_services.title; each entry is a list of
(step_name, step_description) pairs.

The Nepali counterparts live in nepali_content.py (auto-generated by
app/translate_seed.py) and are merged with these in main.py.
"""

# Step-level progress checklist created when a user starts an application
# for a service. Keyed by gov_services.title; each entry is a list of
# (step_name, step_description) pairs shown in the app's progress tracker.
STEP_TEMPLATES = {
    "Citizenship Certificate Copy": [
        ("Gather Documents", (
            "Collect the Ward Office recommendation letter, both parents' citizenship "
            "certificates, birth registration, school/character certificate, parents' "
            "marriage certificate, two passport-size photos and an NPR 10 revenue stamp."
        )),
        ("Obtain Ward Office Recommendation", (
            "Visit your local Ward Office with the original documents. The ward certifies "
            "your identity and permanent residence before you file at the DAO."
        )),
        ("Submit Application at DAO", (
            "Fill the Schedule-1 application form, attach the revenue stamp, and submit it at "
            "the DAO's citizenship section together with your adult witness."
        )),
        ("Verification & Collection", (
            "Attend verification if a spot inquiry (Sarjaamin) is called, then collect your "
            "certificate — often the same day or within a few working days."
        )),
    ],
    "NID Registration": [
        ("Pre-Enroll Online", (
            "Log in or create an account at donidcr.gov.np and verify your mobile number with "
            "the OTP. Start a 'New Enrollment' and fill in details that match your citizenship "
            "certificate exactly."
        )),
        ("Upload Documents & Book Appointment", (
            "Upload your citizenship certificate (and marriage certificate if applicable), "
            "select your enrollment centre and appointment date, then print your token slip."
        )),
        ("Biometric Enrollment", (
            "Attend in person — face and ears clearly visible. Complete photo, ten-finger "
            "fingerprints, iris scan, and digital signature; review the report on the spot."
        )),
        ("Receive NIN Confirmation", (
            "Get your interim National Identity Number confirmation, usable immediately while "
            "the physical card is being printed."
        )),
        ("Collect NID Card", (
            "Collect your physical NID card from the enrollment centre when notified — this can "
            "take a few weeks to a few months depending on the national backlog."
        )),
    ],
    "E-Passport Apply": [
        ("Pre-Enrollment Online", (
            "Complete the online pre-enrollment form at emrtds.nepalpassport.gov.np with your "
            "citizenship and NID details."
        )),
        ("Select Office & Book Appointment", (
            "Choose the Department of Passports HQ, a District Administration Office, or an "
            "embassy/consulate, then pick an appointment date and time slot."
        )),
        ("Pay Fee & Print Slip", (
            "Pay the applicable fee (e.g. NPR 5,000 for a regular 34-page passport) and print "
            "your pre-enrollment slip."
        )),
        ("Attend Biometric Appointment", (
            "Appear in person with all original documents. Live photo, fingerprints and document "
            "verification are captured on-site."
        )),
        ("Collect Passport", (
            "Collect your passport from the office where you applied — DAOs typically take 7–15 "
            "working days, embassies 4–8 weeks."
        )),
    ],
    "Driving License": [
        ("Register on DoTM Portal", (
            "Log in at applydlnew.dotm.gov.np (or via Nagarik App) and complete your profile; "
            "scan the QR code on your NID to auto-fill much of the form."
        )),
        ("Upload Documents & Pay Fee", (
            "Upload citizenship, blood group certificate, eye test certificate (Category B and "
            "above), medical certificate and photographs, then pay the government fee online."
        )),
        ("Book & Attend Verification", (
            "Book an appointment at your chosen Transport Management Office and visit on the "
            "date with original documents for verification and biometric enrollment."
        )),
        ("Pass Written Exam", (
            "Sit the written knowledge test at the office (or a computer-based test in some "
            "regions)."
        )),
        ("Pass Practical Trial", (
            "If you pass the written exam you are scheduled for the practical trial test — you "
            "need a minimum of ~70/100 points."
        )),
        ("Collect License", (
            "Pay the final issuance fee, receive a temporary driving slip while the smart card "
            "prints, then collect your license when notified (typically 15–30 working days)."
        )),
    ],
}

# Fallback when a service has no specific step template defined.
DEFAULT_STEP_TEMPLATE = [
    ("Submit Application", "Submit your application and supporting documents to the responsible office."),
    ("Processing", "The responsible department reviews and processes your application."),
    ("Collection", "Collect your certificate/card/license once processing is complete."),
]
